### ISSUE TITLE
Calling get-setf-expansion with 0 

### ISSUE THREAD

**Issue by Yehouda** [phoe/binding-arrows#5] opened 2021-10-15 12:36 UTC
on LispWorks calling `(ql:quickload "binding-arrows/test")` (with ***compiler-break-on-error*** set to T), gives the error as in the attached file: 
[get-setf-expansion-with-zero.txt](https://github.com/phoe/binding-arrows/files/7353392/get-setf-expansion-with-zero.txt)

It happens when it expands the form `(setf (cond-> 0 (t (nthcdr list)) (t cdr) (nil car) (t cdr) (t car)) 42)` in the test **setf-cond->** in "t/test.lisp". 
The check by **invalid-place-p** that was added in https://github.com/phoe/binding-arrows/commit/7c864702e47c35ab63dd1afe8940a7ce163a9dea prevents it from generating a bad setter, so if **get-setf-expansion** returns a bogus setter it will work. But on LispWorks it errors, 

The standard for **get-setf-expansion**   http://www.lispworks.com/documentation/HyperSpec/Body/f_get_se.htm says it takes a _place_, but does not say what it does if it is given an invalid _place_. SO some implementations will error, and some will not. It is therefore betetr to check before any call to  **get-setf-expansion** that may get an invalid _place.._

**Comment by phoe** [comment] 2021-10-18 19:05
Thanks for finding this out! I understand that the fix would be to never call `get-setf-expansion` with a value that does not denote a valid place, since this is the part where UB might happen.

I don't have the resources to make that fix myself, so I'll need to either delay it into undefined future or ask a person reading these words to try and provide a patch that I'll be happy to merge.

**Comment by githubforced2fabad** [comment] 2024-03-09 00:45
I encountered this on ECL too. Would this be as simple as putting an `ignore-errors` around the call to `get-setf-expansion`?

**Comment by phoe** [comment] 2024-03-09 00:52
Don't think it would be _that_ simple, since the current four `get-setf-expansion` calls are expected to return five meaningful values that are understandable by the rest of the code. One hacky idea would be to wrap `ignore-errors` around the functions that call it, so that they return e.g. zero meaningful values instead; another would be to never call `get-setf-expansion` if the place is `invalid-place-p`, and then have the rest of the code handle such situations, but I don't have the resources to write that patch at the moment.

**Comment by githubforced2fabad** [comment] 2024-03-09 17:47
[0001-Only-call-get-setf-expansion-on-valid-places.txt](https://github.com/phoe/binding-arrows/files/14547257/0001-Only-call-get-setf-expansion-on-valid-places.txt)
Here is a patch. Github does not allow `.patch` files, so I had to rename it to `.txt`, but it is a patch file.

**Comment by phoe** [comment] 2024-03-10 01:14
Thanks. My only worry with this patch is - is an "empty" SETF expansion correct as per the specification? As in, is `(values nil nil nil (constantly nil) (constantly nil))` a valid SETF expansion? Won't passing such an expansion into the rest of the code introduce any sort of problems?

**Comment by githubforced2fabad** [comment] 2024-03-10 05:16
Yes. I did get a little confused there. I think part of the problem is that I do not understand what `cond->` is supposed to do? I assume that `(setf (cond-> 0) 4)` is indeed invalid and so is `(setf (cond-> 0 (nil x)) 4)` (assume x is some local variable). Doesn't this mean that the failing test is actually supposed to fail? You can't `setf 0`.

**Comment by githubforced2fabad** [comment] 2024-03-14 00:10
Perhaps I do not understand something completely. Anyway, here is a patch using my initial approach, but returns a standard compliant setf expansion for invalid places. It passes all the tests on ECL and SBCL and CCL and ABCL.

[0001-Only-call-get-setf-expansion-on-valid-places-v2.txt](https://github.com/phoe/binding-arrows/files/14594951/0001-Only-call-get-setf-expansion-on-valid-places-v2.txt)

**Comment by githubforced2fabad** [comment] 2024-03-21 01:18
Is there any update on this?

**Comment by phoe** [comment] 2024-03-21 07:58
Yes, please prepare a GitHub MR so I can merge it.

**Comment by githubforced2fabad** [comment] 2024-03-21 17:55
What do you think about this:

Unfortunately, I have trouble with github (forced 2 factor authentication). I know it is not the usual github workflow, and I apologize for that. Here are some instructions and options to make it easy.

I have already supplied a patch file that can be applied locally, then pushed here (upstream).

```sh
$ git am -- 0001-Only-call-get-setf-expansion-on-valid-places-v2.txt
$ git push origin main
```

Alternatively, If you really want to pull, I have created a fork at https://git.sr.ht/~charje/binding-arrows. You can add the remote and then do a pull from there, then push to here (upstream).

```sh
$ git remote add charje https://git.sr.ht/~charje/binding-arrows
$ git pull --rebase charje main
$ git push origin main
```

**Comment by githubforced2fabad** [comment] 2024-03-28 18:15
Hello Phoe, I just wanted to check in and see if there have been any updates on this. 🙂

**Comment by phoe** [comment] 2024-03-28 19:52
Thanks; finally found a moment to focus and be able to do this. Patch applied, let me close the issue.

**Closed by phoe** 2024-03-28 19:52 UTC
Labels: bug, good first issue

**Comment by githubforced2fabad** [comment] 2024-03-28 19:54
Thank you so much. :heart:
